// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQxDdZKWDV1osEjC7NuUo3MpQIKqNr1aU',
    appId: '1:331994280197:web:3d7171a2685caa8cbe476c',
    messagingSenderId: '331994280197',
    projectId: 'flutter-examples-a7037',
    authDomain: 'flutter-examples-a7037.firebaseapp.com',
    storageBucket: 'flutter-examples-a7037.appspot.com',
    measurementId: 'G-PNDWP9N5LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQZQkoSjGJxnnZWxzxuOiiEGcK5_n7nRU',
    appId: '1:331994280197:android:3e3d7787adeaade3be476c',
    messagingSenderId: '331994280197',
    projectId: 'flutter-examples-a7037',
    storageBucket: 'flutter-examples-a7037.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCga9xaaesvhuw9ynk_ErKKMW-3VSneW9M',
    appId: '1:331994280197:ios:3b821f3fb651e9bfbe476c',
    messagingSenderId: '331994280197',
    projectId: 'flutter-examples-a7037',
    storageBucket: 'flutter-examples-a7037.appspot.com',
    iosBundleId: 'com.example.learningFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCga9xaaesvhuw9ynk_ErKKMW-3VSneW9M',
    appId: '1:331994280197:ios:3b821f3fb651e9bfbe476c',
    messagingSenderId: '331994280197',
    projectId: 'flutter-examples-a7037',
    storageBucket: 'flutter-examples-a7037.appspot.com',
    iosBundleId: 'com.example.learningFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQxDdZKWDV1osEjC7NuUo3MpQIKqNr1aU',
    appId: '1:331994280197:web:278330ebf94ecf36be476c',
    messagingSenderId: '331994280197',
    projectId: 'flutter-examples-a7037',
    authDomain: 'flutter-examples-a7037.firebaseapp.com',
    storageBucket: 'flutter-examples-a7037.appspot.com',
    measurementId: 'G-2SCT2CLJHS',
  );
}
